export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  llmApiKey: process.env.LLM_API_KEY ?? "",
  mailjetApiKey: process.env.MAILJET_API_KEY ?? "",
  mailjetApiSecret: process.env.MAILJET_API_SECRET ?? "",
  mailjetFromEmail: process.env.MAILJET_FROM_EMAIL ?? "",
  mailjetFromName: process.env.MAILJET_FROM_NAME ?? "",
  cronSecret: process.env.CRON_SECRET ?? "",
  publicBaseUrl: process.env.PUBLIC_BASE_URL ?? "",
  googleClientId: process.env.GOOGLE_CLIENT_ID ?? "",
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET ?? "",
  recaptchaSecretKey: process.env.RECAPTCHA_SECRET_KEY ?? "",
  appUrl: process.env.APP_URL ?? "http://localhost:3000",
  cookieDomain: process.env.COOKIE_DOMAIN ?? "",
};
